version: "2"
services:
  web-patron:
    container_name: web-patron
    build: ./
    environment:
      CONFIG_FILE: /config/config.yml
      NODE_ENV: production
      PALACE_CPW_FEATURE_OPDS2: ${PALACE_CPW_FEATURE_OPDS2:-false}
    volumes:
      - ./config:/app/config
    ports:
      - 3000:3000
