const chalk = require("chalk");
const { readVersionInfo } = require("./src/config/read-version");
const { NODE_ENV, REACT_AXE } = process.env;

const log = (...message) =>
  console.log(chalk.blue("app info") + "  -", ...message);

// Read version info from the file generated by dunamai in CI.
// Falls back to git commands for local dev; null if neither is available.
let _version = {};
try { _version = require("./src/_version.json"); } catch {}

const { APP_VERSION, GIT_COMMIT_SHA, GIT_BRANCH } = readVersionInfo(_version);

// compute the release stage of the app
const RELEASE_STAGE =
  NODE_ENV === "production" && GIT_BRANCH === "production"
    ? "production"
    : NODE_ENV === "production" && GIT_BRANCH === "qa"
    ? "qa"
    : "development";

const BUILD_ID = `${APP_VERSION}-${GIT_BRANCH}.${GIT_COMMIT_SHA}`;

// log some info to the console for the record.
log(`CONFIG_FILE: ${process.env.CONFIG_FILE ?? "(resolved at runtime)"}`);
log(`GIT_BRANCH: ${GIT_BRANCH}`);
log(`APP_VERSION: ${APP_VERSION}`);
log(`NODE_ENV: ${NODE_ENV}`);
log(`RELEASE_STAGE: ${RELEASE_STAGE}`);
log(`BUILD_ID: ${BUILD_ID}`);
log(`BUGSNAG_API_KEY: ${process.env.BUGSNAG_API_KEY ?? "(not set)"}`);
log(`GTM_ID: ${process.env.GTM_ID ?? "(not set)"}`);

const config = {
  output: "standalone",
  transpilePackages: ["@thepalaceproject/webpub-viewer"],
  env: {
    REACT_AXE: REACT_AXE,
    APP_VERSION: APP_VERSION ?? undefined,
    BUILD_ID,
    GIT_BRANCH: GIT_BRANCH ?? undefined,
    GIT_COMMIT_SHA: GIT_COMMIT_SHA ?? undefined,
    RELEASE_STAGE
  },
  async rewrites() {
    return [{ source: "/version.json", destination: "/api/version.json" }];
  },
  productionBrowserSourceMaps: true,
  generateBuildId: async () => BUILD_ID,
  webpack: (config, { dev, isServer, _defaultLoaders, webpack }) => {
    console.log(
      chalk.cyan("info  -"),
      `Building ${isServer ? "server" : "client"} files using Webpack version ${
        webpack.version
      }.`
    );
    // Perform customizations to webpack config
    // Important: return the modified config
    !isServer &&
      config.plugins.push(
        new webpack.IgnorePlugin({ resourceRegExp: /jsdom$/ })
      );
    // react-axe should only be bundled when REACT_AXE=true
    !REACT_AXE === "true" &&
      config.plugins.push(
        new webpack.IgnorePlugin({ resourceRegExp: /react-axe$/ })
      );
    // Fixes dependency on "fs" module.
    // We don't (and can't) depend on this in client-side code.
    if (!isServer) {
      config.resolve.fallback.fs = false;
    }

    return config;
  }
};

const withBundleAnalyzer = require("@next/bundle-analyzer")({
  enabled: process.env.ANALYZE === "true"
});
module.exports = {
  ...withBundleAnalyzer(config),
  distDir: "_next",
  generateBuildId: async () => {
    if (process.env.BUILD_ID) {
      return process.env.BUILD_ID;
    } else {
      return `${new Date().getTime()}`;
    }
  }
};
