# # This workflow will publish the qa image to docker hub
name: Publish qa

# # action will only run when a pull request to the beta branch is closed.
on:
  pull_request:
    branches: [qa]
    types: [closed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish_beta:
    name: Publish qa image to Docker Hub
    # only run if the PR is merged.
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Use Node Version from nvmrc
        uses: actions/setup-node@v1
        with: { node-version: "${{ steps.nvmrc.outputs.NODE_VERSION }}" }

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get short SHA
        id: get_sha
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"

      - name: Build and push to Docker Hub
        id: publish_docker_hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            thepalaceproject/web-patron:beta
            thepalaceproject/web-patron:beta.${{ steps.get_sha.outputs.short_sha }}
            thepalaceproject/web-patron:qa
            thepalaceproject/web-patron:qa.${{ steps.get_sha.outputs.short_sha }}
          # allows us to install the private axisnow package
          build-args: |
            github_token=${{ secrets.GH_PACKAGES_TOKEN }}
