# # This workflow will publish the qa image to the Docker registry
name: Publish qa

# # action will only run when a pull request to the qa branch is closed.
on:
  pull_request:
    branches: [qa]
    types: [closed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish_qa:
    name: Publish qa image to Docker registry
    env:
      REGISTRY_HOST: ghcr.io
      # Don't push the Docker image if the `NO_DOCKER_IMAGE` secret is set.
      IMAGE_PUSH_ENABLED: ${{ secrets.NO_DOCKER_IMAGE == null }}

    # only run if the PR is merged.
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: Use Node Version from nvmrc
        uses: actions/setup-node@v1
        with: { node-version: "${{ steps.nvmrc.outputs.NODE_VERSION }}" }

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to the Docker registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate tags for web-patron image
        id: web-patron-tags
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY_HOST }}/${{ github.repository_owner }}/web-patron
          tags: |
            type=semver,pattern={{major}}.{{minor}},priority=10
            type=semver,pattern={{version}},priority=20
            type=ref,event=branch,priority=30
            type=sha,priority=40

      - name: Build and push web-patron image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: ${{ env.IMAGE_PUSH_ENABLED }}
          tags: ${{ steps.web-patron-tags.outputs.tags }}
