# This workflow will publish an image to the Docker registry on pushes to the main branch.
name: Publish Release

on:
  push:
    branches: [main]

jobs:
  publish:
    name: Publish image to Docker registry
    env:
      REGISTRY_HOST: ghcr.io
      # Don't push the Docker image if the `NO_DOCKER_IMAGE` secret is set.
      IMAGE_PUSH_ENABLED: ${{ secrets.NO_DOCKER_IMAGE == null }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: nvmrc
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT

      - name: Use Node Version from nvmrc
        uses: actions/setup-node@v4
        with: { node-version: "${{ steps.nvmrc.outputs.NODE_VERSION }}" }

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to the Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate tags for web-patron image
        id: web-patron-tags
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_HOST }}/${{ github.repository_owner }}/web-patron
          tags: |
            type=semver,pattern={{major}}.{{minor}},priority=10
            type=semver,pattern={{version}},priority=20
            type=ref,event=branch,priority=30
            type=sha,priority=40

      - name: Build and push web-patron image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: ${{ env.IMAGE_PUSH_ENABLED }}
          tags: ${{ steps.web-patron-tags.outputs.tags }}
